project_id = "qkjjyiymzaouqslzbxrp"

[functions.consultar-cedula]
verify_jwt = false

[functions.send-recordatorio-cita]
verify_jwt = false

[functions.daily-agenda-notifications]
verify_jwt = false

[functions.daily-reminder-cron]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false
